INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris once audited the IRS');
INSERT INTO chuck_norris_facts (text) VALUES ('In Air Force basic training Chuck Norris got a military buzz cut in the morning and had a mullet by that evening.');
INSERT INTO chuck_norris_facts (text) VALUES ('When Alexander Bell invented the telephone he had 3 missed calls from Chuck Norris');
INSERT INTO chuck_norris_facts (text) VALUES ('There used to be a street named after Chuck Norris, but it was changed because nobody crosses Chuck Norris and lives.');
INSERT INTO chuck_norris_facts (text) VALUES ('If you rate this 5 roundhouse kicks, then Chuck Norris WILL roundhouse kick Justin Bieber''s ass.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris has already been to Mars; that''s why there are no signs of life.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris died 20 years ago, Death just hasn''t built up the courage to tell him yet.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris and Superman once fought each other on a bet. The loser had to start wearing his underwear on the outside of his pants.');
INSERT INTO chuck_norris_facts (text) VALUES ('Some magicans can walk on water, Chuck Norris can swim through land.');
INSERT INTO chuck_norris_facts (text) VALUES ('Fear of spiders is aracnaphobia, fear of tight spaces is chlaustraphobia, fear of Chuck Norris is called Logic');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris counted to infinity - twice.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris is the reason why Waldo is hiding.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris once urinated in a semi truck''s gas tank as a joke....that truck is now known as Optimus Prime.');
INSERT INTO chuck_norris_facts (text) VALUES ('Death once had a near-Chuck Norris experience');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can slam a revolving door.');
INSERT INTO chuck_norris_facts (text) VALUES ('When the Boogeyman goes to sleep every night, he checks his closet for Chuck Norris.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris doesn''t flush the toilet, he scares the sh*t out of it');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris once kicked a horse in the chin. Its decendants are known today as Giraffes.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can win a game of Connect Four in only three moves.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can cut through a hot knife with butter');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris once got bit by a rattle snake........ After three days of pain and agony ..................the rattle snake died');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris will never have a heart attack. His heart isn''t nearly foolish enough to attack him.');
INSERT INTO chuck_norris_facts (text) VALUES ('There is no theory of evolution. Just a list of animals Chuck Norris allows to live.');
INSERT INTO chuck_norris_facts (text) VALUES ('When Chuck Norris does a pushup, he isn''t lifting himself up, he''s pushing the Earth down.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris doesn’t wear a watch. HE decides what time it is.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can light a fire by rubbing two ice-cubes together.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris doesn''t read books. He stares them down until he gets the information he wants.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can kill 2 stones with 1 bird.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris made a Happy Meal cry.');
INSERT INTO chuck_norris_facts (text) VALUES ('Some people wear Superman pajamas. Superman wears Chuck Norris pajamas.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can set ants on fire with a magnifying glass. At night.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris is the only man to ever defeat a brick wall in a game of tennis.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris knows the last digit of pi.');
INSERT INTO chuck_norris_facts (text) VALUES ('If you spell Chuck Norris in Scrabble, you win. Forever.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris played Russian Roulette with a fully loaded gun and won.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can speak brail');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris was in all 6 Star Wars movies............... As The Force.');
INSERT INTO chuck_norris_facts (text) VALUES ('The movie "Aliens vs Predators" was orginally supposed to be Aliens and Predators vs Chuck Norris but that movie only lasted 8 seconds.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris has a grizzly bear carpet in his room. The bear isn''t dead, it is just afraid to move.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris never needs a flash light, he just stares into the darkness and it moves out of the way.');
INSERT INTO chuck_norris_facts (text) VALUES ('When life gave Chuck Norris lemons, he made lemonade, a 9 inch hunting knife, an AK-47, and a playpen for his pet scorpion.');
INSERT INTO chuck_norris_facts (text) VALUES ('Aliens DO indeed exist. They just know better than to visit a planet that Chuck Norris is on.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris was supposed to play the lead role in Mission: Impossible. He was replaced by Tom Cruise because the tittle wouldn''t make any sense.');
INSERT INTO chuck_norris_facts (text) VALUES ('When Clint Eastwood called the .44 Magnum "the most powerful handgun in the world" he didn''t know about the thumb and index finger of Chuck Norris');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris sleeps with a pillow under his gun.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can touch MC Hammer');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris CAN believe it''s not butter.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris once won a Scrabble tournament despite getting only Z''s and Q''s in his rack.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris can make a stuffed animal bleed.');
INSERT INTO chuck_norris_facts (text) VALUES ('Chuck Norris'' hand is the only hand that can beat a Royal Flush.');
INSERT INTO chuck_norris_facts (text) VALUES ('They once made a Chuck Norris toilet paper, but there was a problem: It wouldn''t take shit from anybody.');
